name: simple_quick_calendar
description: A calendar widget with simple look-like and quickly-started.
version: 0.0.2
homepage: https://github.com/chongin12/simple-quick-calendar

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter